// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/get-saved-jobs.ts
import { defineTool, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/jobs.ts
import { ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Authenticated caller required");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/jobs.ts
var TRUST_SCORE_NOTE = "Trust Score reflects listing-quality signals only. It is not a hiring probability and does not measure personal fit.";
var LIST_COLUMNS = "id, job_title, company_name, company_location, job_url, application_status, trust_score, ghost_risk, careers_verification, follow_up_date, posted_date, created_at, updated_at";
var DETAIL_COLUMNS = LIST_COLUMNS + ", description, notes, signals, has_salary, investigation, rating, ghost_score, scoring_version";
function ownerClient(ctx) {
  if (!ctx.isAuthenticated()) throw new ToolError("Sign in to your GhostJob account to use this tool.");
  const userId = ctx.getUserId();
  if (!userId) throw new ToolError("Sign in to your GhostJob account to use this tool.");
  return { supabase: supabaseForUser(ctx), userId };
}
function toJson(value) {
  if (value === null || value === void 0) return null;
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return value;
  if (Array.isArray(value)) return value.map(toJson);
  if (typeof value === "object") {
    const out = {};
    for (const [k, v] of Object.entries(value)) out[k] = toJson(v);
    return out;
  }
  return String(value);
}
function isClosed(job) {
  return job.careers_verification === "closed_conflict" || job.application_status === "rejected" || job.application_status === "ghosted";
}
var toJobSummary = (j) => ({
  id: j.id,
  job_title: j.job_title,
  company_name: j.company_name,
  company_location: j.company_location ?? null,
  job_url: j.job_url ?? null,
  application_status: j.application_status,
  trust_score: j.trust_score ?? null,
  ghost_risk: j.ghost_risk ?? "unknown",
  careers_verification: j.careers_verification ?? "unknown",
  follow_up_date: j.follow_up_date ?? null,
  posted_date: j.posted_date ?? null,
  saved_at: j.created_at,
  updated_at: j.updated_at,
  explicitly_closed: isClosed(j)
});

// src/lib/mcp/tools/get-saved-jobs.ts
var get_saved_jobs_default = defineTool({
  name: "get_saved_jobs",
  title: "Get saved jobs",
  description: "List the signed-in user's saved GhostJob jobs, newest first, with pagination.",
  inputSchema: {
    page: z.number().int().min(1).default(1).describe("Page number, starting at 1."),
    page_size: z.number().int().min(1).max(50).default(20).describe("Jobs per page (max 50)."),
    status: z.enum(["saved", "applied", "interviewing", "offer", "rejected", "ghosted"]).optional().describe("Optional application status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false, openWorldHint: false },
  handler: async ({ page, page_size, status }, ctx) => {
    const { supabase, userId } = ownerClient(ctx);
    const from = (page - 1) * page_size;
    let q = supabase.from("scanned_jobs").select(LIST_COLUMNS, { count: "exact" }).eq("user_id", userId).order("created_at", { ascending: false }).range(from, from + page_size - 1);
    if (status) q = q.eq("application_status", status);
    const { data, error, count } = await q;
    if (error) throw new ToolError2("Could not load saved jobs.");
    const jobs = (data ?? []).map(toJobSummary);
    const total = count ?? jobs.length;
    const result = { jobs, page, page_size, total, has_more: from + jobs.length < total, note: TRUST_SCORE_NOTE };
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/get-saved-job.ts
import { defineTool as defineTool2, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_saved_job_default = defineTool2({
  name: "get_saved_job",
  title: "Get saved job",
  description: "Return one of the signed-in user's saved jobs with its description, posting evidence, notes, and follow-up date.",
  inputSchema: { job_id: z2.string().uuid().describe("ID of a saved job from get_saved_jobs.") },
  annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false, openWorldHint: false },
  handler: async ({ job_id }, ctx) => {
    const { supabase, userId } = ownerClient(ctx);
    const { data, error } = await supabase.from("scanned_jobs").select(DETAIL_COLUMNS).eq("id", job_id).eq("user_id", userId).maybeSingle();
    if (error) throw new ToolError3("Could not load this job.");
    if (!data) throw new ToolError3("No saved job with that ID was found in your account.");
    const row = data;
    const job = {
      ...toJobSummary(row),
      description: row.description ?? null,
      notes: row.notes ?? null,
      evidence: {
        has_salary: row.has_salary === null ? "unknown" : row.has_salary,
        signals: toJson(row.signals),
        investigation: toJson(row.investigation),
        rating: row.rating ?? "unknown",
        legacy_ghost_score: row.ghost_score ?? null,
        scoring_version: row.scoring_version ?? null
      }
    };
    const result = { job, note: TRUST_SCORE_NOTE + " Fields marked unknown or null were not verified; do not treat them as negative." };
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/get-today.ts
import { defineTool as defineTool3, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var MINUTES = { follow_up: 10, apply: 30, review: 10 };
var get_today_default = defineTool3({
  name: "get_today",
  title: "Get today's plan",
  description: "Suggest up to three job-search actions that fit a time budget, based on the user's saved jobs and due follow-ups.",
  inputSchema: {
    minutes: z3.number().int().min(5).max(480).default(60).describe("Time available today, in minutes.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false, openWorldHint: false },
  handler: async ({ minutes }, ctx) => {
    const { supabase, userId } = ownerClient(ctx);
    const { data, error } = await supabase.from("scanned_jobs").select(LIST_COLUMNS).eq("user_id", userId).order("updated_at", { ascending: false }).limit(200);
    if (error) throw new ToolError4("Could not load saved jobs.");
    const jobs = data ?? [];
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const candidates = [];
    for (const j of jobs) {
      if (j.follow_up_date && j.follow_up_date.slice(0, 10) <= today && ["applied", "interviewing", "offer"].includes(j.application_status)) {
        candidates.push({ job_id: j.id, job_title: j.job_title, company_name: j.company_name, action: "follow_up", estimated_minutes: MINUTES.follow_up, reason: `Follow-up was due ${j.follow_up_date.slice(0, 10)}.` });
      }
    }
    const applyable = jobs.filter((j) => j.application_status === "saved" && !isClosed(j)).sort((a, b) => (b.trust_score ?? -1) - (a.trust_score ?? -1));
    for (const j of applyable) {
      const verified = j.careers_verification === "verified_match";
      const reason = verified ? "Saved and matched on the employer's careers site." : j.trust_score == null ? "Saved; listing evidence is still unknown, so check the posting before applying." : `Saved; Trust Score ${j.trust_score} (listing quality, not hiring odds or fit).`;
      candidates.push({ job_id: j.id, job_title: j.job_title, company_name: j.company_name, action: "apply", estimated_minutes: MINUTES.apply, reason });
    }
    const actions = [];
    let used = 0;
    for (const c of candidates) {
      if (actions.length >= 3) break;
      if (used + c.estimated_minutes > minutes) continue;
      actions.push(c);
      used += c.estimated_minutes;
    }
    const excluded_closed = jobs.filter((j) => j.application_status === "saved" && isClosed(j)).length;
    const result = { minutes_budget: minutes, minutes_planned: used, actions: actions.map((a) => ({ job_id: a.job_id, job_title: a.job_title, company_name: a.company_name, action: a.action, estimated_minutes: a.estimated_minutes, reason: a.reason })), excluded_closed_roles: excluded_closed, note: TRUST_SCORE_NOTE };
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/index.ts
var projectRef = "auevehneizminspolipf";
var mcp_default = defineMcp({
  name: "ghostjob",
  title: "GhostJob",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's saved GhostJob jobs. Use get_saved_jobs to browse, get_saved_job for one job's details and evidence, and get_today for up to three suggested actions within a time budget. Trust Score measures listing-quality signals only \u2014 never present it as hiring probability or personal fit. Treat unknown evidence as unverified, not negative. These tools cannot write, scan, apply, or message anyone.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_saved_jobs_default, get_saved_job_default, get_today_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
